easyacg:
  storage:
    mode: SMB
    local:
      path:
    smb:
      host: Easyacg
      share-name: personal_folder
      username: brahma
      password: Sdfqwer@1
      base-path: \Photos\MobileBackup\vivo X Flod3 Pro\2024\07
    r2:
      bucketName: easyacg-small
      accountId: 4babbbc62a173e234c3bb185c76a41f5
      accessKey: 07af84fb73f27dfb0fe347b7dcb36e0b
      secretKey: 91259032ff52eadb21e3b7cf4b8743bb29b1450a7cc1a7134bb469c900cc7fd7
      endpoint: https://${easyacg.storage.r2.accountId}.r2.cloudflarestorage.com
