server:
  port: 8083

spring:
  profiles:
    active: pro

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.brahma.entity.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid

logging:
  level:
    com.brahma: debug
