spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyacg?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

auto-table:
  enable: true
  recordSql:
    enable: true
    recordType: custom
    folderPath: sql