server:
  port: 8083

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/brahma
    url: jdbc:mysql://120.25.3.63:3306/brahma
    username: root
    password: xxf2023

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.brahma.entity.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid

logging:
  level:
    com.brahma: debug
