easyacg:
  version: 1.0.0

server:
  port: 8083

spring:
  profiles:
    active: pro

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.easyacg.*.mybatis
  type-enums-package: com.easyacg.*.mybatis.enums
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      id-type: assign_uuid

logging:
  level:
    com.easyacg: debug
