easyacg:
  storage:
    mode: SMB
    local:
      path:
    smb:
      host: Easyacg
      share-name: personal_folder
      username: brahma
      password: Sdfqwer@1
      base-path: \Photos\MobileBackup\vivo X Flod3 Pro\2024\07
